export const ADD_ITEM = 'ADD_ITEM';
export const SET_WEATHER = 'SET_WEATHER';
export const REFRESH_WEATHER = 'REFRESH_WEATHER';
export const GET_WEATHER_FORECAST = 'GET_WEATHER_FORECAST';
export const SET_WEATHER_FORECAST = 'SET_WEATHER_FORECAST';
export const DELETE_ITEM = 'DELETE_ITEM';
